spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:file:./data/bookings
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
  security:
    enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/ticketmaster
server:
  port: 8094

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
kafka:
  bootstrap:
    servers: localhost:9093, localhost:9092