version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: start-dev
    environment:
      # Keycloak Bootstrap admin variables
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # Database Connections
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network

  postgres:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      # FIX: Mount directly to /var/lib/postgresql to comply with 18+ standards
      - postgres_data:/var/lib/postgresql
    networks:
      - keycloak_network

volumes:
  # Isolated volume definition
  postgres_data:

networks:
  keycloak_network:
    driver: bridge
