spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=event_service
    username: event_service_role
    password: secure_event_password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: event_service
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
  security:
    enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/ticketmaster
server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,heapdump
  endpoint:
    heapdump:
        enabled: true
    health:
      show-details: when-authorized