spring:
  application:
    name: event-service
  datasource:
    url: jdbc:h2:file:./data/events
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
  security:
    enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ticketmaster
server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,heapdump
  endpoint:
    heapdump:
      enabled: true
    health:
      show-details: when-authorized